name: Google Cloud Run Action
description: Templates and deploys applications to Google Cloud Run in a single step.
author: 'Michael Reichenbach (Silthus)'
branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  # Essential template inputs
  chart:
    description: 'Helm chart to use for templating. Defaults to the Google Cloud Run chart.'
    required: false
    default: 'oci://ghcr.io/helmless/google-cloudrun-service'
  chart_version:
    description: 'Version of the Helm chart to use.'
    required: false
    default: 'latest'
  files:
    description: 'Glob patterns of value files to include when templating the chart.'
    required: false
    default: 'values.yaml'
  
  # Essential deploy inputs
  dry_run:
    description: 'If true, only validate the configuration without deploying.'
    required: false
    default: 'false'

outputs:
  manifests_deployed:
    description: 'The number of manifests that were deployed.'
    value: ${{ steps.deploy.outputs.manifests_deployed }}
  workloads:
    description: 'JSON array of all deployed Cloud Run workloads with their details (name, type, region, project).'
    value: ${{ steps.deploy.outputs.workloads }}
  
runs:
  using: composite
  steps:
    - name: 📄 Template Cloud Run Manifest
      id: template
      uses: helmless/action@v1 
      with:
        chart: ${{ inputs.chart }}
        chart_version: ${{ inputs.chart_version }}
        files: ${{ inputs.files }}
        print_manifest: 'true'
    
    - name: 🚀 Deploy to Cloud Run
      id: deploy
      uses: ./deploy
      with:
        path: ${{ steps.template.outputs.output_dir }}
        dry_run: ${{ inputs.dry_run }}
