name: Google Cloud Run Deploy
description: Deploys a rendered Helmless manifest to Google Cloud Run. Can deploy either a single manifest or a directory of manifests.
author: 'Michael Reichenbach (Silthus)'
branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  path:
    description: 'The path to the manifest file or directory containing manifest files.'
    required: false
    default: 'helmless_manifest.yaml'
  dry_run:
    description: 'If true, only validate the configuration without deploying.'
    required: false
    default: 'false'
outputs:
  manifests_deployed:
    description: 'The number of manifests that were deployed.'
    value: ${{ steps.deploy.outputs.deployed_count }}
  workloads:
    description: 'JSON array of all deployed Cloud Run workloads with their details (name, type, region, project).'
    value: ${{ steps.deploy.outputs.workloads }}

runs:
  using: composite
  steps:
    - name: 📦 Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: 🚀 Deploy to Cloud Run
      id: deploy
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
        DRY_RUN: ${{ inputs.dry_run }}
        SCRIPTS_DIR: ${{ github.action_path }}/scripts
      run: ${{ github.action_path }}/entrypoint.sh 