---
# Source: cloudrun/templates/cloudrun.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: e2e-test-service
  labels:
  annotations:
    run.googleapis.com/launch-stage: GA
    run.googleapis.com/ingress: all
    run.googleapis.com/region: europe-west1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: 'true'
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300

      containers:
        - image: us-docker.pkg.dev/cloudrun/container/hello
          env:
            - name: 'COLOR'
              value: 'blue'
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'

          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: null
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: null
            periodSeconds: null
          readinessProbe:
            failureThreshold: null
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: null
            periodSeconds: null
          startupProbe:
            failureThreshold: null
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: null
            periodSeconds: null
